In [1]:
import numpy as np

In [2]:

a= np.array([1,2,3,4,5])
b= np.array([4,5,6,7,8])
print(a,b)
print(type(a))
print(type(b))


[1 2 3 4 5] [4 5 6 7 8]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [3]:
print(a+b)
print(a*b)
print(a-b)

[ 5  7  9 11 13]
[ 4 10 18 28 40]
[-3 -3 -3 -3 -3]


2d matrix syntax
np.array([[],[],[]])

In [5]:
n2 = np.array([[1,2],[2,3]])
print(n2)
print(n2.shape) #no of nows and colums
print(n2.ndim) #no of dimesions
print(n2.dtype) #data type of the elements

[[1 2]
 [2 3]]
(2, 2)
2
int32


In [6]:
# a matrix of number fromm 1 to 100 with a gap of 5
np.arange(1,100,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [12]:
# a matrix of numbers from 1 to 10 with 25 elements
np.linspace(1,10,25)

array([ 1.   ,  1.375,  1.75 ,  2.125,  2.5  ,  2.875,  3.25 ,  3.625,
        4.   ,  4.375,  4.75 ,  5.125,  5.5  ,  5.875,  6.25 ,  6.625,
        7.   ,  7.375,  7.75 ,  8.125,  8.5  ,  8.875,  9.25 ,  9.625,
       10.   ])

In [14]:
# a matrix of number of random number from 1 to 10 and shape 2x3
np.random.randint(1,10, size=(2,3))

array([[1, 4, 2],
       [3, 5, 8]])

In [10]:
np.random.uniform(size=(3,3))

array([[0.47578327, 0.25089677, 0.53152036],
       [0.20649815, 0.66242301, 0.47337417],
       [0.23894219, 0.70711585, 0.55719955]])